### Raiz da aplicação
GET http://localhost:5143/

### Listagem de produtos
GET http://localhost:5143/produto/listar

### Busca de produtos por nome
GET http://localhost:5143/produto/buscar/Arroz

### Cadastro de produtos
POST http://localhost:5143/produto/cadastrar
Content-Type: application/json

{
    "nome" : "Arroz",
    "descricao" : "Alimento",
    "valor" : 15
}

### Remoção de produtos
DELETE http://localhost:5143/produto/deletar/12eaf39e-0670-415f-bdc9-99862827db37
Content-Type: application/json

{
    "nome" : "Arroz",
    "descricao" : "Alimento",
    "valor" : 15
}

### Alterar produto
PUT http://localhost:5143/produto/alterar/997adaae-736f-4423-a66c-0053cdeb7644
Content-Type: application/json

{
    "nome" : "Arroz Alterado",
    "descricao" : "Alimento",
    "valor" : 15
}

